### ISSUE TITLE
DNN Shows error Conversion failed when converting the nvarchar value '/Sigma/Use' to data type int. 

### ISSUE THREAD

**Issue by rajasajidmanzoor** [DNNCommunity/DNNCommunity.Home#1]
Hello,

I am new to DNN. I Have installed DNN on my IIS Server. After install, Home pages looked fine. But when i tried logging In, it shows Error Page.
 I have explored over internet but did not found any reliable solutions.  See Error Details below

Exception: Conversion failed when converting the nvarchar value '/Sigma/Use' to data type int.

Inner Exception: Conversion failed when converting the nvarchar value '/Sigma/Use' to data type int.

Exception Stack:

 at System.Data.SqlClient.SqlConnection. (SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)  at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)

   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)

   at System.Data.SqlClient.SqlDataReader.Read()

   at DotNetNuke.Common.Utilities.CBO.CreateObjectFromReader(Type objType, IDataReader dr, Boolean closeReader)

   at DotNetNuke.Common.Utilities.CBO.FillObject[TObject](IDataReader dr)

   at DotNetNuke.Entities.Modules.ModuleController.GetModuleByDefinition(Int32 portalId, String definitionName)

   at DotNetNuke.UI.ControlPanels.ControlBar.GetTabURL(List`1 additionalParams, String toolName, Boolean isHostTool, String moduleFriendlyName, String controlKey, Boolean showAsPopUp)

   at DotNetNuke.UI.ControlPanels.ControlBar.BuildToolUrl(String toolName, Boolean isHostTool, String moduleFriendlyName, String controlKey, String navigateUrl, Boolean showAsPopUp)

   at ASP.admin_controlpanel_controlbar_ascx.__RenderControlPanel(HtmlTextWriter __w, Control parameterContainer)

   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)

   at System.Web.UI.WebControls.WebControl.RenderContents(HtmlTextWriter writer)

   at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer)

   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)

   at ASP.admin_controlpanel_controlbar_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer)

   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)

   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)

   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)

   at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer)

   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)

   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)

   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)

   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)

   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)

   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)

   at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer)

   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)

   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

I am using DNN Version 8.. 

Please let me know how can i fix this issue.

**Comment by kanm2015** [comment]
Might be related to this, 
https://dnntracker.atlassian.net/browse/DNN-8503

**Comment by valadas** [comment]
For some reason, I have no write access on this project, can someone close this issue, or if still an issue to move it to https://github.com/dnnsoftware/Dnn.Platform

**Comment by EPTamminga** [comment]
Wrong repo. This just an intro text repo.
